---
- name: Gather Disk Utilization Information
  hosts: all  # Replace with your host group or individual host IP/address
  gather_facts: yes

  tasks:
    - name: Check Disk Utilization
      shell: df -h
      register: df_output

    - name: Display Disk Utilization
      debug:
        var: df_output.stdout_lines
      when: "'%' in df_output.stdout_lines[1]"

    - name: Show Disk Utilization Status
      debug:
        msg: "Disk Utilization is HIGH (>80%)"
      when: "item.split()[4] | int > 80"
      with_items: "{{ df_output.stdout_lines[1:] }}"
      loop_control:
        loop_var: item

    - name: Show Disk Utilization Status
      debug:
        msg: "Disk Utilization is NORMAL (<=80%)"
      when: "item.split()[4] | int <= 80"
      with_items: "{{ df_output.stdout_lines[1:] }}"
      loop_control:
        loop_var: item

